// Auto-generated by Supabase. Regenerate via:
//   mcp__supabase__generate_typescript_types
// or
//   npx supabase gen types typescript --project-id lbezyjstbgwahpsideoo --schema public
//
// Do not hand-edit the structure of this file; edit the database schema instead.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5";
  };
  public: {
    Tables: {
      circle_invites: {
        Row: {
          accepted_at: string | null;
          circle_id: string;
          created_at: string;
          expires_at: string;
          id: string;
          invite_code: string;
          invited_email: string | null;
          inviter_id: string;
          status: string;
        };
        Insert: {
          accepted_at?: string | null;
          circle_id: string;
          created_at?: string;
          expires_at?: string;
          id?: string;
          invite_code: string;
          invited_email?: string | null;
          inviter_id: string;
          status?: string;
        };
        Update: {
          accepted_at?: string | null;
          circle_id?: string;
          created_at?: string;
          expires_at?: string;
          id?: string;
          invite_code?: string;
          invited_email?: string | null;
          inviter_id?: string;
          status?: string;
        };
        Relationships: [
          {
            foreignKeyName: "circle_invites_circle_id_fkey";
            columns: ["circle_id"];
            isOneToOne: false;
            referencedRelation: "circles";
            referencedColumns: ["id"];
          },
        ];
      };
      circle_memberships: {
        Row: {
          buddy_id: string;
          circle_id: string;
          id: string;
          joined_at: string;
          via_invite: string | null;
        };
        Insert: {
          buddy_id: string;
          circle_id: string;
          id?: string;
          joined_at?: string;
          via_invite?: string | null;
        };
        Update: {
          buddy_id?: string;
          circle_id?: string;
          id?: string;
          joined_at?: string;
          via_invite?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "circle_memberships_circle_id_fkey";
            columns: ["circle_id"];
            isOneToOne: false;
            referencedRelation: "circles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "circle_memberships_via_invite_fkey";
            columns: ["via_invite"];
            isOneToOne: false;
            referencedRelation: "circle_invites";
            referencedColumns: ["id"];
          },
        ];
      };
      circles: {
        Row: {
          created_at: string;
          id: string;
          owner_id: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          owner_id: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          owner_id?: string;
        };
        Relationships: [];
      };
      onboarding_responses: {
        Row: {
          accountability_mode: string;
          active_intervention: boolean;
          completed_at: string | null;
          created_at: string;
          desired_outcomes: string[];
          focus_habits: string[];
          risk_situations: string[];
          risk_times: string[];
          support_modes: string[];
          tone_of_voice: string;
          triggers: string[];
          updated_at: string;
          user_id: string;
        };
        Insert: {
          accountability_mode?: string;
          active_intervention?: boolean;
          completed_at?: string | null;
          created_at?: string;
          desired_outcomes?: string[];
          focus_habits?: string[];
          risk_situations?: string[];
          risk_times?: string[];
          support_modes?: string[];
          tone_of_voice?: string;
          triggers?: string[];
          updated_at?: string;
          user_id: string;
        };
        Update: {
          accountability_mode?: string;
          active_intervention?: boolean;
          completed_at?: string | null;
          created_at?: string;
          desired_outcomes?: string[];
          focus_habits?: string[];
          risk_situations?: string[];
          risk_times?: string[];
          support_modes?: string[];
          tone_of_voice?: string;
          triggers?: string[];
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          circle_privacy: Json;
          created_at: string;
          display_name: string | null;
          email: string;
          id: string;
          onboarded_at: string | null;
          updated_at: string;
        };
        Insert: {
          circle_privacy?: Json;
          created_at?: string;
          display_name?: string | null;
          email: string;
          id: string;
          onboarded_at?: string | null;
          updated_at?: string;
        };
        Update: {
          circle_privacy?: Json;
          created_at?: string;
          display_name?: string | null;
          email?: string;
          id?: string;
          onboarded_at?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      accept_invite: { Args: { p_code: string }; Returns: string };
      complete_onboarding: { Args: Record<string, never>; Returns: string };
      ensure_my_invite_code: { Args: Record<string, never>; Returns: string };
      get_invite_preview: {
        Args: { p_code: string };
        Returns: {
          expires_at: string;
          invite_code: string;
          inviter_display_name: string;
          inviter_id: string;
          status: string;
        }[];
      };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">;
type DefaultSchema =
  DatabaseWithoutInternals[Extract<keyof Database, "public">];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;
