// Auto-generated by Supabase. Regenerate via:
//   mcp__supabase__generate_typescript_types
//
// Do not hand-edit the structure of this file; edit the database schema instead.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  __InternalSupabase: { PostgrestVersion: "14.5" };
  public: {
    Tables: {
      bad_habits_master: {
        Row: { created_at: string; id: string; is_default: boolean; name: string; sort_order: number };
        Insert: { created_at?: string; id: string; is_default?: boolean; name: string; sort_order: number };
        Update: { created_at?: string; id?: string; is_default?: boolean; name?: string; sort_order?: number };
        Relationships: [];
      };
      circle_invites: {
        Row: { accepted_at: string | null; circle_id: string; created_at: string; expires_at: string; id: string; invite_code: string; invited_email: string | null; inviter_id: string; status: string };
        Insert: { accepted_at?: string | null; circle_id: string; created_at?: string; expires_at?: string; id?: string; invite_code: string; invited_email?: string | null; inviter_id: string; status?: string };
        Update: { accepted_at?: string | null; circle_id?: string; created_at?: string; expires_at?: string; id?: string; invite_code?: string; invited_email?: string | null; inviter_id?: string; status?: string };
        Relationships: [
          { foreignKeyName: "circle_invites_circle_id_fkey"; columns: ["circle_id"]; isOneToOne: false; referencedRelation: "circles"; referencedColumns: ["id"] },
        ];
      };
      circle_memberships: {
        Row: { buddy_id: string; circle_id: string; id: string; joined_at: string; via_invite: string | null };
        Insert: { buddy_id: string; circle_id: string; id?: string; joined_at?: string; via_invite?: string | null };
        Update: { buddy_id?: string; circle_id?: string; id?: string; joined_at?: string; via_invite?: string | null };
        Relationships: [
          { foreignKeyName: "circle_memberships_circle_id_fkey"; columns: ["circle_id"]; isOneToOne: false; referencedRelation: "circles"; referencedColumns: ["id"] },
          { foreignKeyName: "circle_memberships_via_invite_fkey"; columns: ["via_invite"]; isOneToOne: false; referencedRelation: "circle_invites"; referencedColumns: ["id"] },
        ];
      };
      circles: {
        Row: { created_at: string; id: string; owner_id: string };
        Insert: { created_at?: string; id?: string; owner_id: string };
        Update: { created_at?: string; id?: string; owner_id?: string };
        Relationships: [];
      };
      habit_logs: {
        Row: { created_at: string; habit_id: string; id: string; log_date: string; notes: string | null; status: string; updated_at: string; user_id: string };
        Insert: { created_at?: string; habit_id: string; id?: string; log_date: string; notes?: string | null; status: string; updated_at?: string; user_id: string };
        Update: { created_at?: string; habit_id?: string; id?: string; log_date?: string; notes?: string | null; status?: string; updated_at?: string; user_id?: string };
        Relationships: [
          { foreignKeyName: "habit_logs_habit_id_fkey"; columns: ["habit_id"]; isOneToOne: false; referencedRelation: "bad_habits_master"; referencedColumns: ["id"] },
        ];
      };
      habit_questions_master: {
        Row: { config: Json | null; created_at: string; default_value: Json; habit_id: string; id: string; metric_key: string | null; options: Json | null; question: string; question_type: string; sort_order: number; unit: string | null };
        Insert: { config?: Json | null; created_at?: string; default_value: Json; habit_id: string; id: string; metric_key?: string | null; options?: Json | null; question: string; question_type: string; sort_order: number; unit?: string | null };
        Update: { config?: Json | null; created_at?: string; default_value?: Json; habit_id?: string; id?: string; metric_key?: string | null; options?: Json | null; question?: string; question_type?: string; sort_order?: number; unit?: string | null };
        Relationships: [
          { foreignKeyName: "habit_questions_master_habit_id_fkey"; columns: ["habit_id"]; isOneToOne: false; referencedRelation: "bad_habits_master"; referencedColumns: ["id"] },
        ];
      };
      onboarding_responses: {
        Row: { accountability_mode: string; active_intervention: boolean; completed_at: string | null; created_at: string; desired_outcomes: string[]; focus_habits: string[]; risk_situations: string[]; risk_times: string[]; support_modes: string[]; tone_of_voice: string; triggers: string[]; updated_at: string; user_id: string };
        Insert: { accountability_mode?: string; active_intervention?: boolean; completed_at?: string | null; created_at?: string; desired_outcomes?: string[]; focus_habits?: string[]; risk_situations?: string[]; risk_times?: string[]; support_modes?: string[]; tone_of_voice?: string; triggers?: string[]; updated_at?: string; user_id: string };
        Update: { accountability_mode?: string; active_intervention?: boolean; completed_at?: string | null; created_at?: string; desired_outcomes?: string[]; focus_habits?: string[]; risk_situations?: string[]; risk_times?: string[]; support_modes?: string[]; tone_of_voice?: string; triggers?: string[]; updated_at?: string; user_id?: string };
        Relationships: [];
      };
      profiles: {
        Row: { circle_privacy: Json; created_at: string; display_name: string | null; email: string; id: string; onboarded_at: string | null; updated_at: string };
        Insert: { circle_privacy?: Json; created_at?: string; display_name?: string | null; email: string; id: string; onboarded_at?: string | null; updated_at?: string };
        Update: { circle_privacy?: Json; created_at?: string; display_name?: string | null; email?: string; id?: string; onboarded_at?: string | null; updated_at?: string };
        Relationships: [];
      };
      reflections: {
        Row: { body: string; created_at: string; id: string; urge_event_id: string | null; user_id: string };
        Insert: { body: string; created_at?: string; id?: string; urge_event_id?: string | null; user_id: string };
        Update: { body?: string; created_at?: string; id?: string; urge_event_id?: string | null; user_id?: string };
        Relationships: [
          { foreignKeyName: "reflections_urge_event_id_fkey"; columns: ["urge_event_id"]; isOneToOne: false; referencedRelation: "urge_events"; referencedColumns: ["id"] },
        ];
      };
      urge_events: {
        Row: { abandoned_at: string | null; audio_used: boolean; completed_at: string | null; habit_id: string; id: string; intensity: number; interruption_action: string | null; started_at: string; status: string; trigger: string; updated_at: string; user_id: string };
        Insert: { abandoned_at?: string | null; audio_used?: boolean; completed_at?: string | null; habit_id: string; id?: string; intensity: number; interruption_action?: string | null; started_at?: string; status?: string; trigger: string; updated_at?: string; user_id: string };
        Update: { abandoned_at?: string | null; audio_used?: boolean; completed_at?: string | null; habit_id?: string; id?: string; intensity?: number; interruption_action?: string | null; started_at?: string; status?: string; trigger?: string; updated_at?: string; user_id?: string };
        Relationships: [
          { foreignKeyName: "urge_events_habit_id_fkey"; columns: ["habit_id"]; isOneToOne: false; referencedRelation: "bad_habits_master"; referencedColumns: ["id"] },
        ];
      };
      user_bad_habits: {
        Row: { active: boolean; created_at: string; habit_id: string; id: string; user_id: string };
        Insert: { active?: boolean; created_at?: string; habit_id: string; id?: string; user_id: string };
        Update: { active?: boolean; created_at?: string; habit_id?: string; id?: string; user_id?: string };
        Relationships: [
          { foreignKeyName: "user_bad_habits_habit_id_fkey"; columns: ["habit_id"]; isOneToOne: false; referencedRelation: "bad_habits_master"; referencedColumns: ["id"] },
        ];
      };
      user_habit_answers: {
        Row: { answer: Json; created_at: string; habit_id: string; id: string; question_id: string; updated_at: string; user_id: string };
        Insert: { answer: Json; created_at?: string; habit_id: string; id?: string; question_id: string; updated_at?: string; user_id: string };
        Update: { answer?: Json; created_at?: string; habit_id?: string; id?: string; question_id?: string; updated_at?: string; user_id?: string };
        Relationships: [
          { foreignKeyName: "user_habit_answers_habit_id_fkey"; columns: ["habit_id"]; isOneToOne: false; referencedRelation: "bad_habits_master"; referencedColumns: ["id"] },
          { foreignKeyName: "user_habit_answers_question_id_fkey"; columns: ["question_id"]; isOneToOne: false; referencedRelation: "habit_questions_master"; referencedColumns: ["id"] },
        ];
      };
    };
    Views: { [_ in never]: never };
    Functions: {
      abandon_urge_event: { Args: { p_event_id: string }; Returns: undefined };
      accept_invite: { Args: { p_code: string }; Returns: string };
      clear_habit_log: { Args: { p_habit_id: string; p_log_date: string }; Returns: undefined };
      complete_onboarding: { Args: Record<string, never>; Returns: string };
      complete_urge_event: { Args: { p_audio_used?: boolean; p_event_id: string; p_log_date: string }; Returns: undefined };
      ensure_my_invite_code: { Args: Record<string, never>; Returns: string };
      get_consistency_history: { Args: { p_from: string; p_to: string }; Returns: { active: number; d: string; fail: number; pct: number; pending: number; success: number }[] };
      get_day_detail: { Args: { p_day: string }; Returns: { habit_id: string; name: string; status: string }[] };
      get_individual_streak: { Args: { p_habit_id: string; p_today: string }; Returns: { best_streak: number; current_streak: number; fail_count: number; success_count: number }[] };
      get_invite_preview: { Args: { p_code: string }; Returns: { expires_at: string; invite_code: string; inviter_display_name: string; inviter_id: string; status: string }[] };
      get_lockd_streak: { Args: { p_today: string }; Returns: { best_streak: number; current_streak: number }[] };
      get_today_consistency: { Args: { p_today: string }; Returns: { active: number; fail: number; pct: number; pending: number; success: number }[] };
      get_urge_pattern: { Args: Record<string, never>; Returns: { event_count: number; peak_count: number; peak_start: number | null }[] };
      log_habit: { Args: { p_habit_id: string; p_log_date: string; p_status: string }; Returns: string };
      save_habit_answers: { Args: { p_answers: Json; p_habit_id: string }; Returns: undefined };
      save_reflection: { Args: { p_body: string; p_urge_event_id?: string }; Returns: string };
      start_urge_event: { Args: { p_habit_id: string; p_intensity: number; p_interruption_action?: string; p_trigger: string }; Returns: string };
      sync_user_bad_habits: { Args: { p_habit_ids: string[] }; Returns: undefined };
    };
    Enums: { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
  };
};

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">;
type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends { Row: infer R }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] & DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends { Row: infer R }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends { Insert: infer I }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends { Insert: infer I }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends { Update: infer U }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends { Update: infer U }
      ? U
      : never
    : never;
